version: 0.0
os: linux
files:
  - source: Telonai/TelonaiBFF/app
    destination: /var/www
  - source: scripts/webapi.service
    destination: /etc/systemd/system
hooks:
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 300
      runas: root