//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeFWCFClient.ETECTransmitterServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorExceptionDetailType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class ErrorExceptionDetailType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageTxtField;
        
        private MeFWCFClient.ETECTransmitterServices.ErrorClassificationCdType ErrorClassificationCdField;
        
        private string ErrorMessageCdField;
        
        private string HostNmField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.ErrorMessageTxtField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageTxtField, value) != true))
                {
                    this.ErrorMessageTxtField = value;
                    this.RaisePropertyChanged("ErrorMessageTxt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public MeFWCFClient.ETECTransmitterServices.ErrorClassificationCdType ErrorClassificationCd
        {
            get
            {
                return this.ErrorClassificationCdField;
            }
            set
            {
                if ((this.ErrorClassificationCdField.Equals(value) != true))
                {
                    this.ErrorClassificationCdField = value;
                    this.RaisePropertyChanged("ErrorClassificationCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessageCd
        {
            get
            {
                return this.ErrorMessageCdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageCdField, value) != true))
                {
                    this.ErrorMessageCdField = value;
                    this.RaisePropertyChanged("ErrorMessageCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HostNm
        {
            get
            {
                return this.HostNmField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HostNmField, value) != true))
                {
                    this.HostNmField = value;
                    this.RaisePropertyChanged("HostNm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorClassificationCdType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum ErrorClassificationCdType1 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYSTEM_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESOURCE_UNAVAILABLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MESSAGE_FORMAT_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SECURITY_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_ERROR = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM", ConfigurationName="ETECTransmitterServices.GetNew2290Schedule1s")]
    public interface GetNew2290Schedule1s
    {
        
        // CODEGEN: Generating message contract since the operation GetNew2290Schedule1s is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetNew2290Schedule1s", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.ETECTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetNew2290Schedule1s", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponse GetNew2290Schedule1s(MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequest request);
    }
       
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum SessionKeyCdType
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum TestCdType
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class MeFNotificationResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string notificationDescField;
        
        private System.DateTime notificationDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NotificationDesc
        {
            get
            {
                return this.notificationDescField;
            }
            set
            {
                this.notificationDescField = value;
                this.RaisePropertyChanged("NotificationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NotificationDt
        {
            get
            {
                return this.notificationDtField;
            }
            set
            {
                this.notificationDtField = value;
                this.RaisePropertyChanged("NotificationDt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sByMsgIDResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string cntField;
        
        private bool moreAvailableIndField;
        
        private base64Binary schedule1AttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool MoreAvailableInd
        {
            get
            {
                return this.moreAvailableIndField;
            }
            set
            {
                this.moreAvailableIndField = value;
                this.RaisePropertyChanged("MoreAvailableInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public base64Binary Schedule1AttMTOM
        {
            get
            {
                return this.schedule1AttMTOMField;
            }
            set
            {
                this.schedule1AttMTOMField = value;
                this.RaisePropertyChanged("Schedule1AttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sByMsgIDRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1ResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private base64Binary schedule1AttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public base64Binary Schedule1AttMTOM
        {
            get
            {
                return this.schedule1AttMTOMField;
            }
            set
            {
                this.schedule1AttMTOMField = value;
                this.RaisePropertyChanged("Schedule1AttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1RequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class ErrorClassificationDetailType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string errorMessageTxtField;
        
        private ErrorClassificationCdType errorClassificationCdField;
        
        private string errorMessageCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.errorMessageTxtField;
            }
            set
            {
                this.errorMessageTxtField = value;
                this.RaisePropertyChanged("ErrorMessageTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorClassificationCdType ErrorClassificationCd
        {
            get
            {
                return this.errorClassificationCdField;
            }
            set
            {
                this.errorClassificationCdField = value;
                this.RaisePropertyChanged("ErrorClassificationCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessageCd
        {
            get
            {
                return this.errorMessageCdField;
            }
            set
            {
                this.errorMessageCdField = value;
                this.RaisePropertyChanged("ErrorMessageCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public enum ErrorClassificationCdType
    {
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        RESOURCE_UNAVAILABLE,
        
        /// <remarks/>
        MESSAGE_FORMAT_ERROR,
        
        /// <remarks/>
        SECURITY_ERROR,
        
        /// <remarks/>
        REQUEST_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class SubmissionErrorType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        private ErrorClassificationDetailType errorClassificationDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorClassificationDetailType ErrorClassificationDetail
        {
            get
            {
                return this.errorClassificationDetailField;
            }
            set
            {
                this.errorClassificationDetailField = value;
                this.RaisePropertyChanged("ErrorClassificationDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string cntField;
        
        private SubmissionErrorType[] eTECSubmissionErrorListField;
        
        private base64Binary schedule1AttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionError", IsNullable=false)]
        public SubmissionErrorType[] ETECSubmissionErrorList
        {
            get
            {
                return this.eTECSubmissionErrorListField;
            }
            set
            {
                this.eTECSubmissionErrorListField = value;
                this.RaisePropertyChanged("ETECSubmissionErrorList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public base64Binary Schedule1AttMTOM
        {
            get
            {
                return this.schedule1AttMTOMField;
            }
            set
            {
                this.schedule1AttMTOMField = value;
                this.RaisePropertyChanged("Schedule1AttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class Get2290Schedule1sRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string[] submissionIdListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionId", IsNullable=false)]
        public string[] SubmissionIdList
        {
            get
            {
                return this.submissionIdListField;
            }
            set
            {
                this.submissionIdListField = value;
                this.RaisePropertyChanged("SubmissionIdList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class GetNew2290Schedule1sResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string cntField;
        
        private bool moreAvailableIndField;
        
        private base64Binary schedule1AttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", Order=0)]
        public string Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool MoreAvailableInd
        {
            get
            {
                return this.moreAvailableIndField;
            }
            set
            {
                this.moreAvailableIndField = value;
                this.RaisePropertyChanged("MoreAvailableInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public base64Binary Schedule1AttMTOM
        {
            get
            {
                return this.schedule1AttMTOMField;
            }
            set
            {
                this.schedule1AttMTOMField = value;
                this.RaisePropertyChanged("Schedule1AttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd")]
    public partial class GetNew2290Schedule1sRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string maxResultCntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string MaxResultCnt
        {
            get
            {
                return this.maxResultCntField;
            }
            set
            {
                this.maxResultCntField = value;
                this.RaisePropertyChanged("MaxResultCnt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNew2290Schedule1sRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNew2290Schedule1sRequest", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest1;
        
        public GetNew2290Schedule1sRequest()
        {
        }
        
        public GetNew2290Schedule1sRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNew2290Schedule1sRequest1 = GetNew2290Schedule1sRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNew2290Schedule1sResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNew2290Schedule1sResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponseType GetNew2290Schedule1sResponse1;
        
        public GetNew2290Schedule1sResponse()
        {
        }
        
        public GetNew2290Schedule1sResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponseType GetNew2290Schedule1sResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNew2290Schedule1sResponse1 = GetNew2290Schedule1sResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetNew2290Schedule1sChannel : MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1s, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetNew2290Schedule1sClient : System.ServiceModel.ClientBase<MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1s>, MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1s
    {
        
        public WCFGetNew2290Schedule1sClient()
        {
        }
        
        public WCFGetNew2290Schedule1sClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }

        public WCFGetNew2290Schedule1sClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetNew2290Schedule1sClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetNew2290Schedule1sClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponse MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1s.GetNew2290Schedule1s(MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequest request)
        {
            return base.Channel.GetNew2290Schedule1s(request);
        }
        
        public MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponseType GetNew2290Schedule1s(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequestType GetNew2290Schedule1sRequest1)
        {
            MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequest inValue = new MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetNew2290Schedule1sRequest1 = GetNew2290Schedule1sRequest1;
            MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1sResponse retVal = ((MeFWCFClient.ETECTransmitterServices.GetNew2290Schedule1s)(this)).GetNew2290Schedule1s(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetNew2290Schedule1sResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM", ConfigurationName="ETECTransmitterServices.Get2290Schedule1s")]
    public interface Get2290Schedule1s
    {
        
        // CODEGEN: Generating message contract since the operation Get2290Schedule1s is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1s", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.ETECTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1s", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponse Get2290Schedule1s(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1sRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1sRequest", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequestType Get2290Schedule1sRequest1;
        
        public Get2290Schedule1sRequest()
        {
        }
        
        public Get2290Schedule1sRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequestType Get2290Schedule1sRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1sRequest1 = Get2290Schedule1sRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1sResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1sResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponseType Get2290Schedule1sResponse1;
        
        public Get2290Schedule1sResponse()
        {
        }
        
        public Get2290Schedule1sResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponseType Get2290Schedule1sResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1sResponse1 = Get2290Schedule1sResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Get2290Schedule1sChannel : MeFWCFClient.ETECTransmitterServices.Get2290Schedule1s, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGet2290Schedule1sClient : System.ServiceModel.ClientBase<MeFWCFClient.ETECTransmitterServices.Get2290Schedule1s>, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1s
    {
        
        public WCFGet2290Schedule1sClient()
        {
        }
        
        public WCFGet2290Schedule1sClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGet2290Schedule1sClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGet2290Schedule1sClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGet2290Schedule1sClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponse MeFWCFClient.ETECTransmitterServices.Get2290Schedule1s.Get2290Schedule1s(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequest request)
        {
            return base.Channel.Get2290Schedule1s(request);
        }
        
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponseType Get2290Schedule1s(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequestType Get2290Schedule1sRequest1)
        {
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequest inValue = new MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.Get2290Schedule1sRequest1 = Get2290Schedule1sRequest1;
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sResponse retVal = ((MeFWCFClient.ETECTransmitterServices.Get2290Schedule1s)(this)).Get2290Schedule1s(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.Get2290Schedule1sResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM", ConfigurationName="ETECTransmitterServices.Get2290Schedule1")]
    public interface Get2290Schedule1
    {
        
        // CODEGEN: Generating message contract since the operation Get2290Schedule1 is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.ETECTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Response Get2290Schedule1(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1Request
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1Request", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1RequestType Get2290Schedule1Request1;
        
        public Get2290Schedule1Request()
        {
        }
        
        public Get2290Schedule1Request(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1RequestType Get2290Schedule1Request1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1Request1 = Get2290Schedule1Request1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1Response
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1Response", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1ResponseType Get2290Schedule1Response1;
        
        public Get2290Schedule1Response()
        {
        }
        
        public Get2290Schedule1Response(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1ResponseType Get2290Schedule1Response1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1Response1 = Get2290Schedule1Response1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Get2290Schedule1Channel : MeFWCFClient.ETECTransmitterServices.Get2290Schedule1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGet2290Schedule1Client : System.ServiceModel.ClientBase<MeFWCFClient.ETECTransmitterServices.Get2290Schedule1>, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1
    {
        
        public WCFGet2290Schedule1Client()
        {
        }
        
        public WCFGet2290Schedule1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGet2290Schedule1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGet2290Schedule1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGet2290Schedule1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Response MeFWCFClient.ETECTransmitterServices.Get2290Schedule1.Get2290Schedule1(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Request request)
        {
            return base.Channel.Get2290Schedule1(request);
        }
        
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1ResponseType Get2290Schedule1(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1RequestType Get2290Schedule1Request1)
        {
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Request inValue = new MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Request();
            inValue.MeFHeader = MeFHeader;
            inValue.Get2290Schedule1Request1 = Get2290Schedule1Request1;
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1Response retVal = ((MeFWCFClient.ETECTransmitterServices.Get2290Schedule1)(this)).Get2290Schedule1(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.Get2290Schedule1Response1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM", ConfigurationName="ETECTransmitterServices.Get2290Schedule1sByMsgID")]
    public interface Get2290Schedule1sByMsgID
    {
        
        // CODEGEN: Generating message contract since the operation Get2290Schedule1sByMsgID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1sByMsgID", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.ETECTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/Get2290Schedule1sByMsgID", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponse Get2290Schedule1sByMsgID(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1sByMsgIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1sByMsgIDRequest", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest1;
        
        public Get2290Schedule1sByMsgIDRequest()
        {
        }
        
        public Get2290Schedule1sByMsgIDRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1sByMsgIDRequest1 = Get2290Schedule1sByMsgIDRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Get2290Schedule1sByMsgIDResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Get2290Schedule1sByMsgIDResponse", Namespace="http://www.irs.gov/a2a/mef/ETECTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponseType Get2290Schedule1sByMsgIDResponse1;
        
        public Get2290Schedule1sByMsgIDResponse()
        {
        }
        
        public Get2290Schedule1sByMsgIDResponse (WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponseType Get2290Schedule1sByMsgIDResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.Get2290Schedule1sByMsgIDResponse1 = Get2290Schedule1sByMsgIDResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface Get2290Schedule1sByMsgIDChannel : MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgID, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGet2290Schedule1sByMsgIDClient : System.ServiceModel.ClientBase<MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgID>, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgID
    {
        
        public WCFGet2290Schedule1sByMsgIDClient()
        {
        }
        
        public WCFGet2290Schedule1sByMsgIDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGet2290Schedule1sByMsgIDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGet2290Schedule1sByMsgIDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGet2290Schedule1sByMsgIDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponse MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgID.Get2290Schedule1sByMsgID(MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequest request)
        {
            return base.Channel.Get2290Schedule1sByMsgID(request);
        }
        
        public MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponseType Get2290Schedule1sByMsgID(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequestType Get2290Schedule1sByMsgIDRequest1)
        {
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequest inValue = new MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.Get2290Schedule1sByMsgIDRequest1 = Get2290Schedule1sByMsgIDRequest1;
            MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgIDResponse retVal = ((MeFWCFClient.ETECTransmitterServices.Get2290Schedule1sByMsgID)(this)).Get2290Schedule1sByMsgID(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.Get2290Schedule1sByMsgIDResponse1;
        }
    }




}
