//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeFWCFClient.MeFMSIServices
{
    using System.Runtime.Serialization;
    using System.Net.Security;

    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorExceptionDetailType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class ErrorExceptionDetailType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageTxtField;
        
        private MeFWCFClient.MeFMSIServices.ErrorClassificationCdType ErrorClassificationCdField;
        
        private string ErrorMessageCdField;
        
        private string HostNmField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.ErrorMessageTxtField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageTxtField, value) != true))
                {
                    this.ErrorMessageTxtField = value;
                    this.RaisePropertyChanged("ErrorMessageTxt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public MeFWCFClient.MeFMSIServices.ErrorClassificationCdType ErrorClassificationCd
        {
            get
            {
                return this.ErrorClassificationCdField;
            }
            set
            {
                if ((this.ErrorClassificationCdField.Equals(value) != true))
                {
                    this.ErrorClassificationCdField = value;
                    this.RaisePropertyChanged("ErrorClassificationCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessageCd
        {
            get
            {
                return this.ErrorMessageCdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageCdField, value) != true))
                {
                    this.ErrorMessageCdField = value;
                    this.RaisePropertyChanged("ErrorMessageCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HostNm
        {
            get
            {
                return this.HostNmField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HostNmField, value) != true))
                {
                    this.HostNmField = value;
                    this.RaisePropertyChanged("HostNm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorClassificationCdType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum ErrorClassificationCdType : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYSTEM_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESOURCE_UNAVAILABLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MESSAGE_FORMAT_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SECURITY_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_ERROR = 4,
    }
    
    
       
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class MeFNotificationResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string notificationDescField;
        
        private System.DateTime notificationDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NotificationDesc
        {
            get
            {
                return this.notificationDescField;
            }
            set
            {
                this.notificationDescField = value;
                this.RaisePropertyChanged("NotificationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NotificationDt
        {
            get
            {
                return this.notificationDtField;
            }
            set
            {
                this.notificationDtField = value;
                this.RaisePropertyChanged("NotificationDt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LoginResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string statusTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusTxt
        {
            get
            {
                return this.statusTxtField;
            }
            set
            {
                this.statusTxtField = value;
                this.RaisePropertyChanged("StatusTxt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LoginRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LogoutResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string statusTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusTxt
        {
            get
            {
                return this.statusTxtField;
            }
            set
            {
                this.statusTxtField = value;
                this.RaisePropertyChanged("StatusTxt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class LogoutRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    

    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class StateParticipantGrpType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string stateCdField;
        
        private string participantProgramsTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StateCd
        {
            get
            {
                return this.stateCdField;
            }
            set
            {
                this.stateCdField = value;
                this.RaisePropertyChanged("StateCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ParticipantProgramsTxt
        {
            get
            {
                return this.participantProgramsTxtField;
            }
            set
            {
                this.participantProgramsTxtField = value;
                this.RaisePropertyChanged("ParticipantProgramsTxt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class GetStateParticipantsListResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int cntField;
        
        private StateParticipantGrpType[] stateParticipantGrpField;
        
        public GetStateParticipantsListResponseType()
        {
            this.cntField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("StateParticipantGrp", Order=1)]
        public StateParticipantGrpType[] StateParticipantGrp
        {
            get
            {
                return this.stateParticipantGrpField;
            }
            set
            {
                this.stateParticipantGrpField = value;
                this.RaisePropertyChanged("StateParticipantGrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class GetStateParticipantsListRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string eTINField;
        
        private string statusTxtField;
        
        private FormStatusGrpType[] formStatusGrpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ETIN
        {
            get
            {
                return this.eTINField;
            }
            set
            {
                this.eTINField = value;
                this.RaisePropertyChanged("ETIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusTxt
        {
            get
            {
                return this.statusTxtField;
            }
            set
            {
                this.statusTxtField = value;
                this.RaisePropertyChanged("StatusTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormStatusGrp", Order=2)]
        public FormStatusGrpType[] FormStatusGrp
        {
            get
            {
                return this.formStatusGrpField;
            }
            set
            {
                this.formStatusGrpField = value;
                this.RaisePropertyChanged("FormStatusGrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class FormStatusGrpType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string formNumField;
        
        private string formStatusTxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FormNum
        {
            get
            {
                return this.formNumField;
            }
            set
            {
                this.formNumField = value;
                this.RaisePropertyChanged("FormNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FormStatusTxt
        {
            get
            {
                return this.formStatusTxtField;
            }
            set
            {
                this.formStatusTxtField = value;
                this.RaisePropertyChanged("FormStatusTxt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINStatusRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string eTINField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ETIN
        {
            get
            {
                return this.eTINField;
            }
            set
            {
                this.eTINField = value;
                this.RaisePropertyChanged("ETIN");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINStatusGrpType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string eTINField;
        
        private string statusTxtField;
        
        private FormStatusGrpType[] formStatusGrpField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ETIN
        {
            get
            {
                return this.eTINField;
            }
            set
            {
                this.eTINField = value;
                this.RaisePropertyChanged("ETIN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusTxt
        {
            get
            {
                return this.statusTxtField;
            }
            set
            {
                this.statusTxtField = value;
                this.RaisePropertyChanged("StatusTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("FormStatusGrp", Order=2)]
        public FormStatusGrpType[] FormStatusGrp
        {
            get
            {
                return this.formStatusGrpField;
            }
            set
            {
                this.formStatusGrpField = value;
                this.RaisePropertyChanged("FormStatusGrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINRetrievalResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private int cntField;
        
        private ETINStatusGrpType[] eTINStatusGrpField;
        
        public ETINRetrievalResponseType()
        {
            this.cntField = 0;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ETINStatusGrp", Order=1)]
        public ETINStatusGrpType[] ETINStatusGrp
        {
            get
            {
                return this.eTINStatusGrpField;
            }
            set
            {
                this.eTINStatusGrpField = value;
                this.RaisePropertyChanged("ETINStatusGrp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public partial class ETINRetrievalRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private TestCdType testCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TestCdType TestCd
        {
            get
            {
                return this.testCdField;
            }
            set
            {
                this.testCdField = value;
                this.RaisePropertyChanged("TestCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="TestCdType", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd")]
    public enum TestCdType
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices", ConfigurationName="MeFMSIServices.EtinRetrieval")]
    public interface EtinRetrieval
    {
        
        // CODEGEN: Generating message contract since the operation EtinRetrieval is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/EtinRetrieval", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFMSIServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/EtinRetrieval", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFMSIServices.EtinRetrievalResponse EtinRetrieval(MeFWCFClient.MeFMSIServices.EtinRetrievalRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtinRetrievalRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ETINRetrievalRequest", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.ETINRetrievalRequestType ETINRetrievalRequest1;
        
        public EtinRetrievalRequest()
        {
        }
        
        public EtinRetrievalRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINRetrievalRequestType ETINRetrievalRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.ETINRetrievalRequest1 = ETINRetrievalRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtinRetrievalResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ETINRetrievalResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.ETINRetrievalResponseType ETINRetrievalResponse1;
        
        public EtinRetrievalResponse()
        {
        }
        
        public EtinRetrievalResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINRetrievalResponseType ETINRetrievalResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.ETINRetrievalResponse1 = ETINRetrievalResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface EtinRetrievalChannel : MeFWCFClient.MeFMSIServices.EtinRetrieval, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFEtinRetrievalClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFMSIServices.EtinRetrieval>, MeFWCFClient.MeFMSIServices.EtinRetrieval
    {
        
        public WCFEtinRetrievalClient()
        {
        }
        
        public WCFEtinRetrievalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFEtinRetrievalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFEtinRetrievalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFEtinRetrievalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFMSIServices.EtinRetrievalResponse MeFWCFClient.MeFMSIServices.EtinRetrieval.EtinRetrieval(MeFWCFClient.MeFMSIServices.EtinRetrievalRequest request)
        {
            return base.Channel.EtinRetrieval(request);
        }
        
        public MeFWCFClient.MeFMSIServices.ETINRetrievalResponseType EtinRetrieval(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINRetrievalRequestType ETINRetrievalRequest1)
        {
            MeFWCFClient.MeFMSIServices.EtinRetrievalRequest inValue = new MeFWCFClient.MeFMSIServices.EtinRetrievalRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.ETINRetrievalRequest1 = ETINRetrievalRequest1;
            MeFWCFClient.MeFMSIServices.EtinRetrievalResponse retVal = ((MeFWCFClient.MeFMSIServices.EtinRetrieval)(this)).EtinRetrieval(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.ETINRetrievalResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices", ConfigurationName="MeFMSIServices.EtinStatus")]
    public interface EtinStatus
    {
        
        // CODEGEN: Generating message contract since the operation EtinStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/EtinStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFMSIServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/EtinStatus", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFMSIServices.EtinStatusResponse EtinStatus(MeFWCFClient.MeFMSIServices.EtinStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtinStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ETINStatusRequest", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.ETINStatusRequestType ETINStatusRequest1;
        
        public EtinStatusRequest()
        {
        }
        
        public EtinStatusRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINStatusRequestType ETINStatusRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.ETINStatusRequest1 = ETINStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EtinStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ETINStatusResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.ETINStatusResponseType ETINStatusResponse1;
        
        public EtinStatusResponse()
        {
        }
        
        public EtinStatusResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINStatusResponseType ETINStatusResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.ETINStatusResponse1 = ETINStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface EtinStatusChannel : MeFWCFClient.MeFMSIServices.EtinStatus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFEtinStatusClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFMSIServices.EtinStatus>, MeFWCFClient.MeFMSIServices.EtinStatus
    {
        
        public WCFEtinStatusClient()
        {
        }
        
        public WCFEtinStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFEtinStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFEtinStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFEtinStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFMSIServices.EtinStatusResponse MeFWCFClient.MeFMSIServices.EtinStatus.EtinStatus(MeFWCFClient.MeFMSIServices.EtinStatusRequest request)
        {
            return base.Channel.EtinStatus(request);
        }
        
        public MeFWCFClient.MeFMSIServices.ETINStatusResponseType EtinStatus(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.ETINStatusRequestType ETINStatusRequest1)
        {
            MeFWCFClient.MeFMSIServices.EtinStatusRequest inValue = new MeFWCFClient.MeFMSIServices.EtinStatusRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.ETINStatusRequest1 = ETINStatusRequest1;
            MeFWCFClient.MeFMSIServices.EtinStatusResponse retVal = ((MeFWCFClient.MeFMSIServices.EtinStatus)(this)).EtinStatus(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.ETINStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices", ConfigurationName="MeFMSIServices.GetStateParticipantsList")]
    public interface GetStateParticipantsList
    {
        
        // CODEGEN: Generating message contract since the operation GetStateParticipantsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/GetStateParticipantsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFMSIServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/GetStateParticipantsList", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponse GetStateParticipantsList(MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateParticipantsListRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStateParticipantsListRequest", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequestType GetStateParticipantsListRequest1;
        
        public GetStateParticipantsListRequest()
        {
        }
        
        public GetStateParticipantsListRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequestType GetStateParticipantsListRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetStateParticipantsListRequest1 = GetStateParticipantsListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStateParticipantsListResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStateParticipantsListResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponseType GetStateParticipantsListResponse1;
        
        public GetStateParticipantsListResponse()
        {
        }
        
        public GetStateParticipantsListResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponseType GetStateParticipantsListResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetStateParticipantsListResponse1 = GetStateParticipantsListResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetStateParticipantsListChannel : MeFWCFClient.MeFMSIServices.GetStateParticipantsList, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetStateParticipantsListClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFMSIServices.GetStateParticipantsList>, MeFWCFClient.MeFMSIServices.GetStateParticipantsList
    {
        
        public WCFGetStateParticipantsListClient()
        {
        }
        
        public WCFGetStateParticipantsListClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetStateParticipantsListClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetStateParticipantsListClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetStateParticipantsListClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponse MeFWCFClient.MeFMSIServices.GetStateParticipantsList.GetStateParticipantsList(MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequest request)
        {
            return base.Channel.GetStateParticipantsList(request);
        }
        
        public MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponseType GetStateParticipantsList(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequestType GetStateParticipantsListRequest1)
        {
            MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequest inValue = new MeFWCFClient.MeFMSIServices.GetStateParticipantsListRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetStateParticipantsListRequest1 = GetStateParticipantsListRequest1;
            MeFWCFClient.MeFMSIServices.GetStateParticipantsListResponse retVal = ((MeFWCFClient.MeFMSIServices.GetStateParticipantsList)(this)).GetStateParticipantsList(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetStateParticipantsListResponse1;
        }
    }
    

    
    
    
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices", ConfigurationName="MeFMSIServices.Logout")]
    public interface Logout
    {
        
        // CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/Logout", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFMSIServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/Logout", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFMSIServices.LogoutResponse Logout(MeFWCFClient.MeFMSIServices.LogoutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutRequest", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.LogoutRequestType LogoutRequest1;
        
        public LogoutRequest()
        {
        }
        
        public LogoutRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LogoutRequestType LogoutRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.LogoutRequest1 = LogoutRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogoutResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.LogoutResponseType LogoutResponse1;
        
        public LogoutResponse()
        {
        }
        
        public LogoutResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LogoutResponseType LogoutResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.LogoutResponse1 = LogoutResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LogoutChannel : MeFWCFClient.MeFMSIServices.Logout, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFLogoutClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFMSIServices.Logout>, MeFWCFClient.MeFMSIServices.Logout
    {
        
        public WCFLogoutClient()
        {
        }
        
        public WCFLogoutClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFLogoutClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFLogoutClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFLogoutClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFMSIServices.LogoutResponse MeFWCFClient.MeFMSIServices.Logout.Logout(MeFWCFClient.MeFMSIServices.LogoutRequest request)
        {
            return base.Channel.Logout(request);
        }
        
        public MeFWCFClient.MeFMSIServices.LogoutResponseType Logout(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LogoutRequestType LogoutRequest1)
        {
            MeFWCFClient.MeFMSIServices.LogoutRequest inValue = new MeFWCFClient.MeFMSIServices.LogoutRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.LogoutRequest1 = LogoutRequest1;
            MeFWCFClient.MeFMSIServices.LogoutResponse retVal = ((MeFWCFClient.MeFMSIServices.Logout)(this)).Logout(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.LogoutResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.irs.gov/a2a/mef/MeFMSIServices", ConfigurationName = "MeFMSIServices.Login", ProtectionLevel = ProtectionLevel.Sign)]
    public interface Login
    {
        
        // CODEGEN: Generating message contract since the operation Login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/Login", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFMSIServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/Login", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFMSIServices.LoginResponse Login(MeFWCFClient.MeFMSIServices.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginRequest", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.LoginRequestType LoginRequest1;
        
        public LoginRequest()
        {
        }
        
        public LoginRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LoginRequestType LoginRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.LoginRequest1 = LoginRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://www.irs.gov/a2a/mef/MeFMSIServices.xsd", Order=0)]
        public MeFWCFClient.MeFMSIServices.LoginResponseType LoginResponse1;
        
        public LoginResponse()
        {
        }
        
        public LoginResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LoginResponseType LoginResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.LoginResponse1 = LoginResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface LoginChannel : MeFWCFClient.MeFMSIServices.Login, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFLoginClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFMSIServices.Login>, MeFWCFClient.MeFMSIServices.Login
    {
        
        public WCFLoginClient()
        {
        }
        
        public WCFLoginClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFLoginClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFLoginClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFLoginClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFMSIServices.LoginResponse MeFWCFClient.MeFMSIServices.Login.Login(MeFWCFClient.MeFMSIServices.LoginRequest request)
        {
            return base.Channel.Login(request);
        }
        
        public MeFWCFClient.MeFMSIServices.LoginResponseType Login(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFMSIServices.LoginRequestType LoginRequest1)
        {
            MeFWCFClient.MeFMSIServices.LoginRequest inValue = new MeFWCFClient.MeFMSIServices.LoginRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.LoginRequest1 = LoginRequest1;
            MeFWCFClient.MeFMSIServices.LoginResponse retVal = ((MeFWCFClient.MeFMSIServices.Login)(this)).Login(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.LoginResponse1;
        }
    }


}
