//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeFWCFClient.MeFTransmitterServices
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorExceptionDetailType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class ErrorExceptionDetailType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ErrorMessageTxtField;
        
        private MeFWCFClient.MeFTransmitterServices.ErrorClassificationCdType ErrorClassificationCdField;
        
        private string ErrorMessageCdField;
        
        private string HostNmField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.ErrorMessageTxtField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageTxtField, value) != true))
                {
                    this.ErrorMessageTxtField = value;
                    this.RaisePropertyChanged("ErrorMessageTxt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public MeFWCFClient.MeFTransmitterServices.ErrorClassificationCdType ErrorClassificationCd
        {
            get
            {
                return this.ErrorClassificationCdField;
            }
            set
            {
                if ((this.ErrorClassificationCdField.Equals(value) != true))
                {
                    this.ErrorClassificationCdField = value;
                    this.RaisePropertyChanged("ErrorClassificationCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMessageCd
        {
            get
            {
                return this.ErrorMessageCdField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ErrorMessageCdField, value) != true))
                {
                    this.ErrorMessageCdField = value;
                    this.RaisePropertyChanged("ErrorMessageCd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HostNm
        {
            get
            {
                return this.HostNmField;
            }
            set
            {
                if ((object.ReferenceEquals(this.HostNmField, value) != true))
                {
                    this.HostNmField = value;
                    this.RaisePropertyChanged("HostNm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorClassificationCdType", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum ErrorClassificationCdType1 : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYSTEM_ERROR = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RESOURCE_UNAVAILABLE = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MESSAGE_FORMAT_ERROR = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SECURITY_ERROR = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        REQUEST_ERROR = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.SendSubmissions")]
    public interface SendSubmissions
    {
        
        // CODEGEN: Generating message contract since the operation SendSubmissions is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/SendSubmissions", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/SendSubmissions", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponse SendSubmissions(MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequest request);
    }   
        
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum SessionKeyCdType
    {
        
        /// <remarks/>
        Y,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public enum TestCdType
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        P,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
    public partial class MeFNotificationResponse : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string notificationDescField;
        
        private System.DateTime notificationDtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NotificationDesc
        {
            get
            {
                return this.notificationDescField;
            }
            set
            {
                this.notificationDescField = value;
                this.RaisePropertyChanged("NotificationDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NotificationDt
        {
            get
            {
                return this.notificationDtField;
            }
            set
            {
                this.notificationDtField = value;
                this.RaisePropertyChanged("NotificationDt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAcksByMsgIDResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool moreAvailableIndField;
        
        private base64Binary acknowledgementListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MoreAvailableInd
        {
            get
            {
                return this.moreAvailableIndField;
            }
            set
            {
                this.moreAvailableIndField = value;
                this.RaisePropertyChanged("MoreAvailableInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary AcknowledgementListAttMTOM
        {
            get
            {
                return this.acknowledgementListAttMTOMField;
            }
            set
            {
                this.acknowledgementListAttMTOMField = value;
                this.RaisePropertyChanged("AcknowledgementListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/05/xmlmime")]
    public partial class base64Binary : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string contentTypeField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public string contentType
        {
            get
            {
                return this.contentTypeField;
            }
            set
            {
                this.contentTypeField = value;
                this.RaisePropertyChanged("contentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAcksByMsgIDRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string messageIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageId
        {
            get
            {
                return this.messageIdField;
            }
            set
            {
                this.messageIdField = value;
                this.RaisePropertyChanged("MessageId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetSubmissionStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private base64Binary statusRecordListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public base64Binary StatusRecordListAttMTOM
        {
            get
            {
                return this.statusRecordListAttMTOMField;
            }
            set
            {
                this.statusRecordListAttMTOMField = value;
                this.RaisePropertyChanged("StatusRecordListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetSubmissionStatusRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetSubmissionsStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SubmissionErrorListType submissionErrorListField;
        
        private base64Binary statusRecordListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SubmissionErrorListType SubmissionErrorList
        {
            get
            {
                return this.submissionErrorListField;
            }
            set
            {
                this.submissionErrorListField = value;
                this.RaisePropertyChanged("SubmissionErrorList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary StatusRecordListAttMTOM
        {
            get
            {
                return this.statusRecordListAttMTOMField;
            }
            set
            {
                this.statusRecordListAttMTOMField = value;
                this.RaisePropertyChanged("StatusRecordListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class SubmissionErrorListType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string cntField;
        
        private SubmissionErrorType[] submissionErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger", IsNullable=true, Order=0)]
        public string Cnt
        {
            get
            {
                return this.cntField;
            }
            set
            {
                this.cntField = value;
                this.RaisePropertyChanged("Cnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SubmissionError", IsNullable=true, Order=1)]
        public SubmissionErrorType[] SubmissionError
        {
            get
            {
                return this.submissionErrorField;
            }
            set
            {
                this.submissionErrorField = value;
                this.RaisePropertyChanged("SubmissionError");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class SubmissionErrorType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        private ErrorClassificationDetailType errorClassificationDetailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorClassificationDetailType ErrorClassificationDetail
        {
            get
            {
                return this.errorClassificationDetailField;
            }
            set
            {
                this.errorClassificationDetailField = value;
                this.RaisePropertyChanged("ErrorClassificationDetail");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class ErrorClassificationDetailType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string errorMessageTxtField;
        
        private ErrorClassificationCdType errorClassificationCdField;
        
        private string errorMessageCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.errorMessageTxtField;
            }
            set
            {
                this.errorMessageTxtField = value;
                this.RaisePropertyChanged("ErrorMessageTxt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorClassificationCdType ErrorClassificationCd
        {
            get
            {
                return this.errorClassificationCdField;
            }
            set
            {
                this.errorClassificationCdField = value;
                this.RaisePropertyChanged("ErrorClassificationCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessageCd
        {
            get
            {
                return this.errorMessageCdField;
            }
            set
            {
                this.errorMessageCdField = value;
                this.RaisePropertyChanged("ErrorMessageCd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public enum ErrorClassificationCdType
    {
        
        /// <remarks/>
        SYSTEM_ERROR,
        
        /// <remarks/>
        RESOURCE_UNAVAILABLE,
        
        /// <remarks/>
        MESSAGE_FORMAT_ERROR,
        
        /// <remarks/>
        SECURITY_ERROR,
        
        /// <remarks/>
        REQUEST_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetSubmissionsStatusRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string[] submissionIdListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionId", IsNullable=false)]
        public string[] SubmissionIdList
        {
            get
            {
                return this.submissionIdListField;
            }
            set
            {
                this.submissionIdListField = value;
                this.RaisePropertyChanged("SubmissionIdList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetNewSubmissionsStatusResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool moreAvailableIndField;
        
        private base64Binary statusRecordListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MoreAvailableInd
        {
            get
            {
                return this.moreAvailableIndField;
            }
            set
            {
                this.moreAvailableIndField = value;
                this.RaisePropertyChanged("MoreAvailableInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary StatusRecordListAttMTOM
        {
            get
            {
                return this.statusRecordListAttMTOMField;
            }
            set
            {
                this.statusRecordListAttMTOMField = value;
                this.RaisePropertyChanged("StatusRecordListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetNewSubmissionsStatusRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string maxResultCntField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string MaxResultCnt
        {
            get
            {
                return this.maxResultCntField;
            }
            set
            {
                this.maxResultCntField = value;
                this.RaisePropertyChanged("MaxResultCnt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAckResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private base64Binary acknowledgementAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public base64Binary AcknowledgementAttMTOM
        {
            get
            {
                return this.acknowledgementAttMTOMField;
            }
            set
            {
                this.acknowledgementAttMTOMField = value;
                this.RaisePropertyChanged("AcknowledgementAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAckRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAcksResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SubmissionErrorListType submissionErrorListField;
        
        private base64Binary acknowledgementListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public SubmissionErrorListType SubmissionErrorList
        {
            get
            {
                return this.submissionErrorListField;
            }
            set
            {
                this.submissionErrorListField = value;
                this.RaisePropertyChanged("SubmissionErrorList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary AcknowledgementListAttMTOM
        {
            get
            {
                return this.acknowledgementListAttMTOMField;
            }
            set
            {
                this.acknowledgementListAttMTOMField = value;
                this.RaisePropertyChanged("AcknowledgementListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetAcksRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string[] submissionIdListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionId", IsNullable=false)]
        public string[] SubmissionIdList
        {
            get
            {
                return this.submissionIdListField;
            }
            set
            {
                this.submissionIdListField = value;
                this.RaisePropertyChanged("SubmissionIdList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetNewAcksResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private bool moreAvailableIndField;
        
        private base64Binary acknowledgementListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool MoreAvailableInd
        {
            get
            {
                return this.moreAvailableIndField;
            }
            set
            {
                this.moreAvailableIndField = value;
                this.RaisePropertyChanged("MoreAvailableInd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary AcknowledgementListAttMTOM
        {
            get
            {
                return this.acknowledgementListAttMTOMField;
            }
            set
            {
                this.acknowledgementListAttMTOMField = value;
                this.RaisePropertyChanged("AcknowledgementListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class GetNewAcksRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string maxResultCntField;
        
        private ExtndAcknowledgementCategoryCdType extndAcknowledgementCategoryCdField;
        
        private bool extndAcknowledgementCategoryCdFieldSpecified;
        
        private GovernmentAgencyTypeCdType governmentAgencyTypeCdField;
        
        private bool governmentAgencyTypeCdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string MaxResultCnt
        {
            get
            {
                return this.maxResultCntField;
            }
            set
            {
                this.maxResultCntField = value;
                this.RaisePropertyChanged("MaxResultCnt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExtndAcknowledgementCategoryCdType ExtndAcknowledgementCategoryCd
        {
            get
            {
                return this.extndAcknowledgementCategoryCdField;
            }
            set
            {
                this.extndAcknowledgementCategoryCdField = value;
                this.RaisePropertyChanged("ExtndAcknowledgementCategoryCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExtndAcknowledgementCategoryCdSpecified
        {
            get
            {
                return this.extndAcknowledgementCategoryCdFieldSpecified;
            }
            set
            {
                this.extndAcknowledgementCategoryCdFieldSpecified = value;
                this.RaisePropertyChanged("ExtndAcknowledgementCategoryCdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public GovernmentAgencyTypeCdType GovernmentAgencyTypeCd
        {
            get
            {
                return this.governmentAgencyTypeCdField;
            }
            set
            {
                this.governmentAgencyTypeCdField = value;
                this.RaisePropertyChanged("GovernmentAgencyTypeCd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GovernmentAgencyTypeCdSpecified
        {
            get
            {
                return this.governmentAgencyTypeCdFieldSpecified;
            }
            set
            {
                this.governmentAgencyTypeCdFieldSpecified = value;
                this.RaisePropertyChanged("GovernmentAgencyTypeCdSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public enum ExtndAcknowledgementCategoryCdType
    {
        
        /// <remarks/>
        CORP,
        
        /// <remarks/>
        EO,
        
        /// <remarks/>
        PART,
        
        /// <remarks/>
        EXCISE,
        
        /// <remarks/>
        IND,
        
        /// <remarks/>
        UNKN,
        
        /// <remarks/>
        ESTRST,
        
        /// <remarks/>
        EMPL,
        
        /// <remarks/>
        all,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public enum GovernmentAgencyTypeCdType
    {
        
        /// <remarks/>
        Federal,
        
        /// <remarks/>
        State,
        
        /// <remarks/>
        both,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class SendSubmissionsResponseType : object, System.ComponentModel.INotifyPropertyChanged
    {
    	private string depositIdField;
        
        private base64Binary submissionRcptListAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string DepositId
	{
	    get
	    {
		return this.depositIdField;
	    }
	    set
	    {
		this.depositIdField = value;
		this.RaisePropertyChanged("DepositId");
	    }
	}
	        
	/// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public base64Binary SubmissionRcptListAttMTOM
        {
            get
            {
                return this.submissionRcptListAttMTOMField;
            }
            set
            {
                this.submissionRcptListAttMTOMField = value;
                this.RaisePropertyChanged("SubmissionRcptListAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class SubmissionDataType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private string submissionIdField;
        
        private System.DateTime electronicPostmarkTsField;
        
        private bool electronicPostmarkTsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SubmissionId
        {
            get
            {
                return this.submissionIdField;
            }
            set
            {
                this.submissionIdField = value;
                this.RaisePropertyChanged("SubmissionId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime ElectronicPostmarkTs
        {
            get
            {
                return this.electronicPostmarkTsField;
            }
            set
            {
                this.electronicPostmarkTsField = value;
                this.RaisePropertyChanged("ElectronicPostmarkTs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ElectronicPostmarkTsSpecified
        {
            get
            {
                return this.electronicPostmarkTsFieldSpecified;
            }
            set
            {
                this.electronicPostmarkTsFieldSpecified = value;
                this.RaisePropertyChanged("ElectronicPostmarkTsSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "3.0.4506.2152")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd")]
    public partial class SendSubmissionsRequestType : object, System.ComponentModel.INotifyPropertyChanged
    {
        
        private SubmissionDataType[] submissionDataListField;
        
        private byte[] submissionsAttMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("SubmissionData")]
        public SubmissionDataType[] SubmissionDataList
        {
            get
            {
                return this.submissionDataListField;
            }
            set
            {
                this.submissionDataListField = value;
                this.RaisePropertyChanged("SubmissionDataList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public byte[] SubmissionsAttMTOM
        {
            get
            {
                return this.submissionsAttMTOMField;
            }
            set
            {
                this.submissionsAttMTOMField = value;
                this.RaisePropertyChanged("SubmissionsAttMTOM");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSubmissionsRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSubmissionsRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequestType SendSubmissionsRequest1;
        
        public SendSubmissionsRequest()
        {
        }
        
        public SendSubmissionsRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequestType SendSubmissionsRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.SendSubmissionsRequest1 = SendSubmissionsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSubmissionsResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSubmissionsResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponseType SendSubmissionsResponse1;
        
        public SendSubmissionsResponse()
        {
        }
        
        public SendSubmissionsResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponseType SendSubmissionsResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.SendSubmissionsResponse1 = SendSubmissionsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface SendSubmissionsChannel : MeFWCFClient.MeFTransmitterServices.SendSubmissions, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFSendSubmissionsClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.SendSubmissions>, MeFWCFClient.MeFTransmitterServices.SendSubmissions
    {
        
        public WCFSendSubmissionsClient()
        {
        }
        
        public WCFSendSubmissionsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFSendSubmissionsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFSendSubmissionsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFSendSubmissionsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponse MeFWCFClient.MeFTransmitterServices.SendSubmissions.SendSubmissions(MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequest request)
        {
            return base.Channel.SendSubmissions(request);
        }

        public MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponseType SendSubmissions(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequestType SendSubmissionsRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequest inValue = new MeFWCFClient.MeFTransmitterServices.SendSubmissionsRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.SendSubmissionsRequest1 = SendSubmissionsRequest1;
            MeFWCFClient.MeFTransmitterServices.SendSubmissionsResponse retVal = ((MeFWCFClient.MeFTransmitterServices.SendSubmissions)(this)).SendSubmissions(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.SendSubmissionsResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetNewAcks")]
    public interface GetNewAcks
    {
        
        // CODEGEN: Generating message contract since the operation GetNewAcks is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetNewAcks", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetNewAcks", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetNewAcksResponse GetNewAcks(MeFWCFClient.MeFTransmitterServices.GetNewAcksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewAcksRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewAcksRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetNewAcksRequestType GetNewAcksRequest1;
        
        public GetNewAcksRequest()
        {
        }
        
        public GetNewAcksRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewAcksRequestType GetNewAcksRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNewAcksRequest1 = GetNewAcksRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewAcksResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewAcksResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetNewAcksResponseType GetNewAcksResponse1;
        
        public GetNewAcksResponse()
        {
        }
        
        public GetNewAcksResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewAcksResponseType GetNewAcksResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNewAcksResponse1 = GetNewAcksResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetNewAcksChannel : MeFWCFClient.MeFTransmitterServices.GetNewAcks, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetNewAcksClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetNewAcks>, MeFWCFClient.MeFTransmitterServices.GetNewAcks
    {
        
        public WCFGetNewAcksClient()
        {
        }
        
        public WCFGetNewAcksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetNewAcksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetNewAcksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetNewAcksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetNewAcksResponse MeFWCFClient.MeFTransmitterServices.GetNewAcks.GetNewAcks(MeFWCFClient.MeFTransmitterServices.GetNewAcksRequest request)
        {
            return base.Channel.GetNewAcks(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetNewAcksResponseType GetNewAcks(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewAcksRequestType GetNewAcksRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetNewAcksRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetNewAcksRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetNewAcksRequest1 = GetNewAcksRequest1;
            MeFWCFClient.MeFTransmitterServices.GetNewAcksResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetNewAcks)(this)).GetNewAcks(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetNewAcksResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetAcks")]
    public interface GetAcks
    {
        
        // CODEGEN: Generating message contract since the operation GetAcks is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetAcks", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetAcks", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetAcksResponse GetAcks(MeFWCFClient.MeFTransmitterServices.GetAcksRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcksRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcksRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAcksRequestType GetAcksRequest1;
        
        public GetAcksRequest()
        {
        }
        
        public GetAcksRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksRequestType GetAcksRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAcksRequest1 = GetAcksRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcksResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcksResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAcksResponseType GetAcksResponse1;
        
        public GetAcksResponse()
        {
        }
        
        public GetAcksResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksResponseType GetAcksResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAcksResponse1 = GetAcksResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetAcksChannel : MeFWCFClient.MeFTransmitterServices.GetAcks, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetAcksClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetAcks>, MeFWCFClient.MeFTransmitterServices.GetAcks
    {
        
        public WCFGetAcksClient()
        {
        }
        
        public WCFGetAcksClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetAcksClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetAcksClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetAcksClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetAcksResponse MeFWCFClient.MeFTransmitterServices.GetAcks.GetAcks(MeFWCFClient.MeFTransmitterServices.GetAcksRequest request)
        {
            return base.Channel.GetAcks(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetAcksResponseType GetAcks(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksRequestType GetAcksRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetAcksRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetAcksRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetAcksRequest1 = GetAcksRequest1;
            MeFWCFClient.MeFTransmitterServices.GetAcksResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetAcks)(this)).GetAcks(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetAcksResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetAck")]
    public interface GetAck
    {
        
        // CODEGEN: Generating message contract since the operation GetAck is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetAck", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetAck", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetAckResponse GetAck(MeFWCFClient.MeFTransmitterServices.GetAckRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAckRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAckRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAckRequestType GetAckRequest1;
        
        public GetAckRequest()
        {
        }
        
        public GetAckRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAckRequestType GetAckRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAckRequest1 = GetAckRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAckResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAckResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAckResponseType GetAckResponse1;
        
        public GetAckResponse()
        {
        }
        
        public GetAckResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAckResponseType GetAckResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAckResponse1 = GetAckResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetAckChannel : MeFWCFClient.MeFTransmitterServices.GetAck, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetAckClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetAck>, MeFWCFClient.MeFTransmitterServices.GetAck
    {
        
        public WCFGetAckClient()
        {
        }
        
        public WCFGetAckClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetAckClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetAckClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetAckClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetAckResponse MeFWCFClient.MeFTransmitterServices.GetAck.GetAck(MeFWCFClient.MeFTransmitterServices.GetAckRequest request)
        {
            return base.Channel.GetAck(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetAckResponseType GetAck(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAckRequestType GetAckRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetAckRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetAckRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetAckRequest1 = GetAckRequest1;
            MeFWCFClient.MeFTransmitterServices.GetAckResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetAck)(this)).GetAck(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetAckResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetNewSubmissionsStatus")]
    public interface GetNewSubmissionsStatus
    {
        
        // CODEGEN: Generating message contract since the operation GetNewSubmissionsStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetNewSubmissionsStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetNewSubmissionsStatus", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponse GetNewSubmissionsStatus(MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewSubmissionsStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewSubmissionsStatusRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequestType GetNewSubmissionsStatusRequest1;
        
        public GetNewSubmissionsStatusRequest()
        {
        }
        
        public GetNewSubmissionsStatusRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequestType GetNewSubmissionsStatusRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNewSubmissionsStatusRequest1 = GetNewSubmissionsStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNewSubmissionsStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNewSubmissionsStatusResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponseType GetNewSubmissionsStatusResponse1;
        
        public GetNewSubmissionsStatusResponse()
        {
        }
        
        public GetNewSubmissionsStatusResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponseType GetNewSubmissionsStatusResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetNewSubmissionsStatusResponse1 = GetNewSubmissionsStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetNewSubmissionsStatusChannel : MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetNewSubmissionsStatusClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatus>, MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatus
    {
        
        public WCFGetNewSubmissionsStatusClient()
        {
        }
        
        public WCFGetNewSubmissionsStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetNewSubmissionsStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetNewSubmissionsStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetNewSubmissionsStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponse MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatus.GetNewSubmissionsStatus(MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequest request)
        {
            return base.Channel.GetNewSubmissionsStatus(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponseType GetNewSubmissionsStatus(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequestType GetNewSubmissionsStatusRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetNewSubmissionsStatusRequest1 = GetNewSubmissionsStatusRequest1;
            MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatusResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetNewSubmissionsStatus)(this)).GetNewSubmissionsStatus(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetNewSubmissionsStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetSubmissionsStatus")]
    public interface GetSubmissionsStatus
    {
        
        // CODEGEN: Generating message contract since the operation GetSubmissionsStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetSubmissionsStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetSubmissionsStatus", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponse GetSubmissionsStatus(MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionsStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionsStatusRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequestType GetSubmissionsStatusRequest1;
        
        public GetSubmissionsStatusRequest()
        {
        }
        
        public GetSubmissionsStatusRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequestType GetSubmissionsStatusRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetSubmissionsStatusRequest1 = GetSubmissionsStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionsStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionsStatusResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponseType GetSubmissionsStatusResponse1;
        
        public GetSubmissionsStatusResponse()
        {
        }
        
        public GetSubmissionsStatusResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponseType GetSubmissionsStatusResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetSubmissionsStatusResponse1 = GetSubmissionsStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetSubmissionsStatusChannel : MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetSubmissionsStatusClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatus>, MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatus
    {
        
        public WCFGetSubmissionsStatusClient()
        {
        }
        
        public WCFGetSubmissionsStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetSubmissionsStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetSubmissionsStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetSubmissionsStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponse MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatus.GetSubmissionsStatus(MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequest request)
        {
            return base.Channel.GetSubmissionsStatus(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponseType GetSubmissionsStatus(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequestType GetSubmissionsStatusRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetSubmissionsStatusRequest1 = GetSubmissionsStatusRequest1;
            MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatusResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetSubmissionsStatus)(this)).GetSubmissionsStatus(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetSubmissionsStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetSubmissionStatus")]
    public interface GetSubmissionStatus
    {
        
        // CODEGEN: Generating message contract since the operation GetSubmissionStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetSubmissionStatus", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetSubmissionStatus", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponse GetSubmissionStatus(MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionStatusRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionStatusRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequestType GetSubmissionStatusRequest1;
        
        public GetSubmissionStatusRequest()
        {
        }
        
        public GetSubmissionStatusRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequestType GetSubmissionStatusRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetSubmissionStatusRequest1 = GetSubmissionStatusRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubmissionStatusResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubmissionStatusResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponseType GetSubmissionStatusResponse1;
        
        public GetSubmissionStatusResponse()
        {
        }
        
        public GetSubmissionStatusResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponseType GetSubmissionStatusResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetSubmissionStatusResponse1 = GetSubmissionStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetSubmissionStatusChannel : MeFWCFClient.MeFTransmitterServices.GetSubmissionStatus, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetSubmissionStatusClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetSubmissionStatus>, MeFWCFClient.MeFTransmitterServices.GetSubmissionStatus
    {
        
        public WCFGetSubmissionStatusClient()
        {
        }
        
        public WCFGetSubmissionStatusClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetSubmissionStatusClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetSubmissionStatusClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetSubmissionStatusClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponse MeFWCFClient.MeFTransmitterServices.GetSubmissionStatus.GetSubmissionStatus(MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequest request)
        {
            return base.Channel.GetSubmissionStatus(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponseType GetSubmissionStatus(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequestType GetSubmissionStatusRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetSubmissionStatusRequest1 = GetSubmissionStatusRequest1;
            MeFWCFClient.MeFTransmitterServices.GetSubmissionStatusResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetSubmissionStatus)(this)).GetSubmissionStatus(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetSubmissionStatusResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM", ConfigurationName="MeFTransmitterServices.GetAcksByMsgID")]
    public interface GetAcksByMsgID
    {
        
        // CODEGEN: Generating message contract since the operation GetAcksByMsgID is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.irs.gov/a2a/mef/mtom/GetAcksByMsgID", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MeFWCFClient.MeFTransmitterServices.ErrorExceptionDetailType), Action="http://www.irs.gov/a2a/mef/mtom/GetAcksByMsgID", Name="ErrorExceptionDetail", Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults = true)]
        MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponse GetAcksByMsgID(MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcksByMsgIDRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcksByMsgIDRequest", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequestType GetAcksByMsgIDRequest1;
        
        public GetAcksByMsgIDRequest()
        {
        }
        
        public GetAcksByMsgIDRequest(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequestType GetAcksByMsgIDRequest1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAcksByMsgIDRequest1 = GetAcksByMsgIDRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAcksByMsgIDResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.irs.gov/a2a/mef/MeFHeader.xsd")]
        public WCFClient.MeFHeaderType MeFHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAcksByMsgIDResponse", Namespace="http://www.irs.gov/a2a/mef/MeFTransmitterServiceMTOM.xsd", Order=0)]
        public MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponseType GetAcksByMsgIDResponse1;
        
        public GetAcksByMsgIDResponse()
        {
        }
        
        public GetAcksByMsgIDResponse(WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponseType GetAcksByMsgIDResponse1)
        {
            this.MeFHeader = MeFHeader;
            this.GetAcksByMsgIDResponse1 = GetAcksByMsgIDResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface GetAcksByMsgIDChannel : MeFWCFClient.MeFTransmitterServices.GetAcksByMsgID, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WCFGetAcksByMsgIDClient : System.ServiceModel.ClientBase<MeFWCFClient.MeFTransmitterServices.GetAcksByMsgID>, MeFWCFClient.MeFTransmitterServices.GetAcksByMsgID
    {
        
        public WCFGetAcksByMsgIDClient()
        {
        }
        
        public WCFGetAcksByMsgIDClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public WCFGetAcksByMsgIDClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public WCFGetAcksByMsgIDClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public WCFGetAcksByMsgIDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponse MeFWCFClient.MeFTransmitterServices.GetAcksByMsgID.GetAcksByMsgID(MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequest request)
        {
            return base.Channel.GetAcksByMsgID(request);
        }
        
        public MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponseType GetAcksByMsgID(ref WCFClient.MeFHeaderType MeFHeader, MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequestType GetAcksByMsgIDRequest1)
        {
            MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequest inValue = new MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDRequest();
            inValue.MeFHeader = MeFHeader;
            inValue.GetAcksByMsgIDRequest1 = GetAcksByMsgIDRequest1;
            MeFWCFClient.MeFTransmitterServices.GetAcksByMsgIDResponse retVal = ((MeFWCFClient.MeFTransmitterServices.GetAcksByMsgID)(this)).GetAcksByMsgID(inValue);
            MeFHeader = retVal.MeFHeader;
            return retVal.GetAcksByMsgIDResponse1;
        }
    }






}
